from __future__ import annotations

import hashlib
import json
import random
import sys
from pathlib import Path

from arte_cognition.canonical_body_checkpoint import checkpoint_dict, restore_runtime
from arte_cognition.cognitive_runtime import PersistentCognitiveRuntime
from arte_cognition.experiment_genesis import ExperimentGenesisEngine
from arte_cognition.projection_generator_transform_grammar import generate_projection_transform_programs
from arte_cognition.projection_scale_genesis import projection_scale_scores
from arte_cognition.representation_genesis import RepresentationAxis
from arte_cognition.world_coupling import (
    HMACWorldReceiptSigner,
    HMACWorldReceiptVerifier,
    WorldOutcomeReceipt,
)


def probe_scale(proposal):
    marker = "probe_scale="
    return float(str(proposal.reason).split(marker, 1)[1].split()[0].rstrip(",;)") )


def axis(label: str, rng: random.Random) -> RepresentationAxis:
    x = f"sensor_{rng.randrange(10000000, 99999999)}"
    z = f"sensor_{rng.randrange(10000000, 99999999)}"
    return RepresentationAxis(
        axis_id=f"AXIS::PROJECTION::{x}|{z}",
        family="PROJECTION",
        inputs=(x, z),
        threshold=0.0,
        direction="GT",
        information_gain=1.0,
        train_support=8,
        positive_partition=(f"{label}-positive",),
        formula=f"(1)*{x} + (1)*{z}",
        coefficients=((x, 1.0), (z, 1.0)),
        bias=0.0,
        status="PROPOSAL_ONLY",
    )


def endpoint_proposals(ax, left, right):
    return ExperimentGenesisEngine(
        projection_margin_multipliers=(float(left), float(right)),
        max_proposals=64,
    ).propose(ax, {ax.inputs[0]: 0.0, ax.inputs[1]: 0.0})


class HiddenExactScaleWorld:
    def __init__(self, target, signer, source_id, challenge_id, context_id, epoch):
        self.target = float(target)
        self.signer = signer
        self.source_id = str(source_id)
        self.challenge_id = str(challenge_id)
        self.context_id = str(context_id)
        self.epoch = int(epoch)

    def execute(self, proposal, arm, value):
        scale = probe_scale(proposal)
        high = 1.0 if abs(scale - self.target) <= 1e-9 else 0.25
        outcome = 0.0 if str(arm).upper() == "LOW" else high
        return self.signer.sign(WorldOutcomeReceipt(
            receipt_id=f"{self.challenge_id}::{proposal.experiment_id}::{arm}",
            experiment_id=proposal.experiment_id,
            axis_id=proposal.axis_id,
            arm=arm,
            intervention_value=float(value),
            outcome=float(outcome),
            source_id=self.source_id,
            context_id=self.context_id,
            challenge_id=self.challenge_id,
            epoch=self.epoch,
            budget_token=f"budget::{self.challenge_id}",
            externally_generated=True,
        ))


def execute(runtime, proposals, target, context, epoch_base, signers, verifier):
    for proposal_index, proposal in enumerate(proposals):
        runtime.memory.remember_experiment(proposal)
        for issuer_index, (issuer, signer) in enumerate(signers.items()):
            pair = runtime.execute_world_intervention(
                proposal,
                HiddenExactScaleWorld(
                    target,
                    signer,
                    f"{context}-{epoch_base}-source-{proposal_index}-{issuer}",
                    f"{context}-{epoch_base}-challenge-{proposal_index}-{issuer}",
                    context,
                    epoch_base + proposal_index * 10 + issuer_index,
                ),
                verifier=verifier,
            )
            if not pair.authority_verified:
                raise AssertionError("authenticated hidden-world pair lost authority")


def capability(runtime, context, target):
    scores = projection_scale_scores(
        (record.proposal for record in runtime.memory.experiments.values()),
        runtime.world_coupling.pairs,
        runtime.world_coupling.min_independent_classes,
        probe_scale,
        context_id=context,
    )
    return float(scores.get(round(float(target), 12), 0.0) >= 0.9)


def select_program(programs, operations, alpha):
    for program in programs:
        if program.operations == tuple(operations) and abs(program.alpha - float(alpha)) <= 1e-12:
            return program
    raise AssertionError("required hidden program was not generated by the grammar")


def choose_bracket(rng, programs, hidden_program, require_target_not_first=False):
    for _ in range(1000):
        left = round(rng.uniform(2.0, 6.0), 6)
        right = round(left * rng.uniform(6.0, 80.0), 6)
        target = hidden_program.apply(left, right)
        if target is None:
            continue
        values = []
        colliders = []
        for program in programs:
            value = program.apply(left, right)
            if value is None:
                continue
            values.append(value)
            if abs(value - target) <= 1e-9 and program.program_id != hidden_program.program_id:
                colliders.append(program.program_id)
        if colliders:
            continue
        if require_target_not_first and values and abs(min(values) - target) <= 1e-9:
            continue
        return left, right, target
    raise AssertionError("could not construct a nondegenerate hidden transform bracket")


def train(runtime, training_brackets, hidden_program, rng, signers, verifier, epoch_offset):
    for index, (left, right, target) in enumerate(training_brackets):
        context = f"train-{rng.randrange(10000000, 99999999)}"
        ax = axis(context, rng)
        runtime.memory.remember_representation(ax)
        execute(runtime, endpoint_proposals(ax, left, right), target, context, epoch_offset + index * 5000, signers, verifier)
        frontier = runtime.projection_transform_frontier(
            context, left, right, max_candidates=64, apply_learned_program=False
        )
        if frontier.status != "SHADOW_TRANSFORM_PROGRAM_GENESIS":
            raise AssertionError(f"unexpected training frontier: {frontier.status}")
        if round(float(target), 12) not in {candidate.scale for candidate in frontier.candidates}:
            raise AssertionError("hidden AST target absent from outcome-independent shadow grammar")
        generated = runtime.generate_projection_transform_interventions(
            ax,
            {ax.inputs[0]: 0.0, ax.inputs[1]: 0.0},
            context,
            left,
            right,
            max_candidates=64,
            apply_learned_program=False,
        )
        execute(runtime, generated, target, context, epoch_offset + 1000 + index * 5000, signers, verifier)


def main(seed_path: str) -> None:
    seed = int(Path(seed_path).read_text().strip())
    rng = random.Random(seed)
    programs = generate_projection_transform_programs()
    hidden = select_program(programs, ("LOG", "LOG"), 0.25)
    wrong_hidden = select_program(programs, ("LOG",), 0.25)

    issuer_a = f"issuer-{rng.randrange(10**7, 10**8)}"
    issuer_b = f"issuer-{rng.randrange(10**7, 10**8)}"
    key_a = hashlib.sha256(f"{seed}:a".encode()).digest()
    key_b = hashlib.sha256(f"{seed}:b".encode()).digest()
    signers = {
        issuer_a: HMACWorldReceiptSigner(issuer_a, key_a),
        issuer_b: HMACWorldReceiptSigner(issuer_b, key_b),
    }
    verifier = HMACWorldReceiptVerifier(
        {issuer_a: key_a, issuer_b: key_b},
        independence_classes={issuer_a: "LAB_A", issuer_b: "LAB_B"},
    )

    training_brackets = (
        choose_bracket(rng, programs, hidden),
        choose_bracket(rng, programs, hidden),
    )
    parent = PersistentCognitiveRuntime()
    train(parent, training_brackets, hidden, rng, signers, verifier, 10000)
    learned = parent.projection_transform_program_policy()
    if learned.operations != ("LOG", "LOG") or learned.alpha != 0.25:
        raise AssertionError(f"wrong transform AST learned: {learned}")

    checkpoint = checkpoint_dict(parent)
    verifierless = restore_runtime(checkpoint)
    if verifierless.projection_transform_program_policy().program_id is not None:
        raise AssertionError("checkpoint restored transform authority without external verifier")

    heldout_left, heldout_right, heldout_target = choose_bracket(
        rng, programs, hidden, require_target_not_first=True
    )
    heldout_context = f"heldout-{rng.randrange(10000000, 99999999)}"
    heldout_axis = axis(heldout_context, rng)

    treatment = restore_runtime(checkpoint, world_verifier=verifier)
    remove = restore_runtime(checkpoint, world_verifier=verifier)
    for runtime in (treatment, remove):
        runtime.memory.remember_representation(heldout_axis)
        execute(
            runtime,
            endpoint_proposals(heldout_axis, heldout_left, heldout_right),
            heldout_target,
            heldout_context,
            50000,
            signers,
            verifier,
        )
        if capability(runtime, heldout_context, heldout_target) != 0.0:
            raise AssertionError("heldout target was already solved by endpoint evidence")

    treatment_frontier = treatment.projection_transform_frontier(
        heldout_context,
        heldout_left,
        heldout_right,
        max_candidates=1,
        apply_learned_program=True,
    )
    treatment_generated = treatment.generate_projection_transform_interventions(
        heldout_axis,
        {heldout_axis.inputs[0]: 0.0, heldout_axis.inputs[1]: 0.0},
        heldout_context,
        heldout_left,
        heldout_right,
        max_candidates=1,
        apply_learned_program=True,
    )
    execute(treatment, treatment_generated, heldout_target, heldout_context, 60000, signers, verifier)
    treatment_capability = capability(treatment, heldout_context, heldout_target)

    remove_frontier = remove.projection_transform_frontier(
        heldout_context,
        heldout_left,
        heldout_right,
        max_candidates=1,
        apply_learned_program=False,
    )
    remove_generated = remove.generate_projection_transform_interventions(
        heldout_axis,
        {heldout_axis.inputs[0]: 0.0, heldout_axis.inputs[1]: 0.0},
        heldout_context,
        heldout_left,
        heldout_right,
        max_candidates=1,
        apply_learned_program=False,
    )
    execute(remove, remove_generated, heldout_target, heldout_context, 60000, signers, verifier)
    remove_capability = capability(remove, heldout_context, heldout_target)

    reset = PersistentCognitiveRuntime()
    reset.memory.remember_representation(heldout_axis)
    execute(
        reset,
        endpoint_proposals(heldout_axis, heldout_left, heldout_right),
        heldout_target,
        heldout_context,
        50000,
        signers,
        verifier,
    )
    reset_generated = reset.generate_projection_transform_interventions(
        heldout_axis,
        {heldout_axis.inputs[0]: 0.0, heldout_axis.inputs[1]: 0.0},
        heldout_context,
        heldout_left,
        heldout_right,
        max_candidates=1,
        apply_learned_program=False,
    )
    execute(reset, reset_generated, heldout_target, heldout_context, 60000, signers, verifier)
    reset_capability = capability(reset, heldout_context, heldout_target)

    wrong_training = tuple(
        (left, right, wrong_hidden.apply(left, right))
        for left, right, _ in training_brackets
    )
    wrong_parent = PersistentCognitiveRuntime()
    train(wrong_parent, wrong_training, wrong_hidden, rng, signers, verifier, 80000)
    wrong_policy = wrong_parent.projection_transform_program_policy()
    if wrong_policy.operations != ("LOG",) or wrong_policy.alpha != 0.25:
        raise AssertionError(f"wrong-control BODY failed to actually learn LOG(.25): {wrong_policy}")
    wrong = restore_runtime(checkpoint_dict(wrong_parent), world_verifier=verifier)
    wrong_context = f"wrong-heldout-{rng.randrange(10000000, 99999999)}"
    wrong_axis = axis(wrong_context, rng)
    wrong.memory.remember_representation(wrong_axis)
    execute(
        wrong,
        endpoint_proposals(wrong_axis, heldout_left, heldout_right),
        heldout_target,
        wrong_context,
        120000,
        signers,
        verifier,
    )
    wrong_frontier = wrong.projection_transform_frontier(
        wrong_context,
        heldout_left,
        heldout_right,
        max_candidates=1,
        apply_learned_program=True,
    )
    wrong_generated = wrong.generate_projection_transform_interventions(
        wrong_axis,
        {wrong_axis.inputs[0]: 0.0, wrong_axis.inputs[1]: 0.0},
        wrong_context,
        heldout_left,
        heldout_right,
        max_candidates=1,
        apply_learned_program=True,
    )
    execute(wrong, wrong_generated, heldout_target, wrong_context, 130000, signers, verifier)
    wrong_capability = capability(wrong, wrong_context, heldout_target)

    named_family_values = {
        "AFFINE": select_program(programs, (), 0.25).apply(heldout_left, heldout_right),
        "GEOMETRIC": select_program(programs, ("LOG",), 0.25).apply(heldout_left, heldout_right),
        "HARMONIC": select_program(programs, ("INV",), 0.25).apply(heldout_left, heldout_right),
    }
    outside_named_three = all(abs(float(value) - heldout_target) > 1e-9 for value in named_family_values.values())

    if treatment_capability != 1.0:
        raise AssertionError("reverified learned compositional AST failed fresh heldout transfer")
    if remove_capability != 0.0 or reset_capability != 0.0 or wrong_capability != 0.0:
        raise AssertionError("REMOVE/RESET/WRONG control did not lose the fresh capability")
    if not outside_named_three:
        raise AssertionError("heldout target collapsed into the original three named interpolation families")

    result = {
        "status": "PASS_BOUNDED_COMPOSITIONAL_TRANSFORM_GENERATOR_AST_AND_DESCENDANT_CAUSAL_TRANSFER",
        "generated_transform_program_count": len(programs),
        "learned_operations": list(learned.operations),
        "learned_alpha": learned.alpha,
        "learned_supporting_contexts": len(learned.supporting_contexts),
        "heldout_bracket": [heldout_left, heldout_right],
        "heldout_target": heldout_target,
        "treatment_candidate_count": len(treatment_frontier.candidates),
        "remove_candidate_count": len(remove_frontier.candidates),
        "wrong_candidate_count": len(wrong_frontier.candidates),
        "treatment_capability": treatment_capability,
        "remove_same_checkpoint_capability": remove_capability,
        "reset_capability": reset_capability,
        "wrong_learned_ast": list(wrong_policy.operations),
        "wrong_learned_alpha": wrong_policy.alpha,
        "wrong_capability": wrong_capability,
        "same_parent_checkpoint_treatment_remove": True,
        "external_authority_required_after_restart": True,
        "verifierless_policy_authority": False,
        "hidden_target_exposed_to_body_before_execution": False,
        "candidate_generation_uses_world_outcomes": False,
        "outside_original_named_three": outside_named_three,
        "named_three_values": named_family_values,
        "primitive_transform_alphabet": ["LOG", "INV"],
        "primitive_transform_alphabet_human_authored": True,
        "unrestricted_transform_operator_genesis": False,
        "foundation_weight_change": False,
        "physical_world": False,
        "independent_organizational_custody": False,
        "global_recursive_acceleration": False,
        "AGI": False,
        "ASI": False,
    }
    print(json.dumps(result, sort_keys=True))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: run_compositional_transform_generator_genesis.py <seed_path>")
    main(sys.argv[1])
