from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Mapping, Sequence, Tuple
import itertools


@dataclass(frozen=True)
class SubgraphEvaluation:
    modules: Tuple[str, ...]
    outcome: float
    compute_cost: float


@dataclass(frozen=True)
class MinimumSufficientSubgraph:
    modules: Tuple[str, ...]
    outcome: float
    compute_cost: float
    outcome_gap_from_full: float
    status: str


class MinimumCausalSubgraphFinder:
    """Find a minimum sufficient cognition subgraph from realized interventions.

    Requires an outcome table generated by actual module-subset interventions.
    A subset is sufficient only if its outcome remains within `tolerance` of the
    full graph. Among sufficient subsets, prefer lower cardinality, then lower
    compute cost, then higher outcome. Missing subset evaluations are never
    imputed as success.
    """

    def __init__(self, tolerance: float = 0.02) -> None:
        self.tolerance = max(0.0, float(tolerance))

    @staticmethod
    def canonical(modules: Iterable[str]) -> Tuple[str, ...]:
        return tuple(sorted(set(modules)))

    def find(
        self,
        full_modules: Sequence[str],
        evaluations: Mapping[Tuple[str, ...], SubgraphEvaluation],
    ) -> MinimumSufficientSubgraph:
        full_key = self.canonical(full_modules)
        full = evaluations.get(full_key)
        if full is None:
            raise ValueError("full graph outcome must be experimentally evaluated")

        sufficient: List[SubgraphEvaluation] = []
        for key, item in evaluations.items():
            canonical = self.canonical(key)
            if canonical != self.canonical(item.modules):
                continue
            if item.outcome + self.tolerance >= full.outcome:
                sufficient.append(item)

        if not sufficient:
            return MinimumSufficientSubgraph(
                modules=full.modules,
                outcome=full.outcome,
                compute_cost=full.compute_cost,
                outcome_gap_from_full=0.0,
                status="FULL_ONLY",
            )

        best = sorted(
            sufficient,
            key=lambda item: (
                len(self.canonical(item.modules)),
                float(item.compute_cost),
                -float(item.outcome),
                self.canonical(item.modules),
            ),
        )[0]
        return MinimumSufficientSubgraph(
            modules=self.canonical(best.modules),
            outcome=float(best.outcome),
            compute_cost=float(best.compute_cost),
            outcome_gap_from_full=float(full.outcome - best.outcome),
            status="MINIMUM_CAUSALLY_SUFFICIENT_SUBGRAPH",
        )

    def required_sparse_ablation_plan(
        self,
        active_modules: Sequence[str],
        include_pairs: bool = True,
        pair_budget: int = 8,
    ) -> List[Tuple[str, ...]]:
        """Produce a bounded intervention plan rather than enumerating 2^N subsets."""
        full = self.canonical(active_modules)
        plan = [full]
        # Single removals identify marginal necessity.
        for module in full:
            plan.append(tuple(m for m in full if m != module))
        if include_pairs:
            for a, b in list(itertools.combinations(full, 2))[:max(0, int(pair_budget))]:
                plan.append(tuple(m for m in full if m not in {a, b}))
        # Stable de-duplication.
        out: List[Tuple[str, ...]] = []
        seen = set()
        for subset in plan:
            if subset not in seen:
                seen.add(subset)
                out.append(subset)
        return out
